using System.Text;

namespace Studio.Core;

/// <summary>Generates a native installer script with the two current wizard pages.</summary>
public static class InnoScript
{
    public static string Generate(StudioProject project, string? projectDirectory)
    {
        ProjectFile.Validate(project);
        var source = ResolveSource(project.InstallFile.Source, projectDirectory);
        var destination = project.InstallFile.Destination.Replace('/', '\\');
        if (!(destination == "{app}" || destination.StartsWith(@"{app}\", StringComparison.Ordinal))
            || destination[5..].IndexOfAny(['{', '}', '"', '*', '?', '<', '>', '|', ':']) >= 0
            || destination[5..].Split('\\').Any(part => part.EndsWith('.') || part.EndsWith(' ')))
            throw Error("ExportDestinationInvalid");
        var directory = project.Pages.Single(p => p.Kind == PageKind.Destination).Destination!.DefaultDirectory;
        foreach (var value in new[] { project.Name, project.AppId, project.AppVersion, source, destination, directory })
            if (value.Contains("{#", StringComparison.Ordinal)) throw Error("ExportPreprocessorUnsupported");

        // Setup directives only strip surrounding quotes; Files parameters unescape doubled quotes.
        var lines = new[]
        {
            "; Generated by Inno Setup Studio. Target compiler: Inno Setup 7.1.",
            "; Application details, one file and native wizard text. Installer language: Dutch.",
            "[Setup]",
            "AppId=" + SetupValue(Literal(project.AppId)),
            "AppName=" + SetupValue(Literal(project.Name)),
            "AppVersion=" + SetupValue(Literal(project.AppVersion)),
            "DefaultDirName=" + SetupValue(directory),
            "DisableWelcomePage=no",
            "DisableDirPage=no",
            "OutputDir=output",
            "OutputBaseFilename=" + SetupValue(project.OutputBaseFileName),
            "",
            "[Languages]",
            "Name: \"dutch\"; MessagesFile: \"compiler:Languages\\Dutch.isl\"",
            "",
            "[Files]",
            "Source: " + Parameter(source) + "; DestDir: " + Parameter(destination),
            ""
        };
        return string.Join("\r\n", lines) + WizardScript.Generate(project);
    }

    public static string ResolveSource(string source, string? projectDirectory)
    {
        if (string.IsNullOrWhiteSpace(source) || source.Any(char.IsControl)
            || source.IndexOfAny(['*', '?', '"', '<', '>', '|']) >= 0)
            throw Error("ExportSourceInvalid");
        if (Path.IsPathRooted(source) && !Path.IsPathFullyQualified(source)) throw Error("ExportSourceInvalid");
        if (!Path.IsPathFullyQualified(source) && string.IsNullOrWhiteSpace(projectDirectory))
            throw Error("ExportSourceNeedsProject");
        var resolved = Path.IsPathFullyQualified(source) ? Path.GetFullPath(source)
            : Path.GetFullPath(source, projectDirectory!);
        if (!File.Exists(resolved)) throw Error("ExportSourceMissing");
        return resolved;
    }

    public static async Task ExportAsync(string path, StudioProject project, string? projectDirectory)
    {
        if (!string.Equals(Path.GetExtension(path), ".iss", StringComparison.OrdinalIgnoreCase))
            throw Error("ExportExtensionInvalid");
        var script = Generate(project, projectDirectory);
        var fullPath = Path.GetFullPath(path);
        if (string.Equals(fullPath, ResolveSource(project.InstallFile.Source, projectDirectory), StringComparison.OrdinalIgnoreCase))
            throw Error("ExportCannotReplaceSource");
        if (File.Exists(fullPath))
        {
            if (await File.ReadAllTextAsync(fullPath) == script) return;
            throw Error("ExportExistingProtected");
        }
        var temporaryPath = fullPath + $".{Guid.NewGuid():N}.tmp";
        try
        {
            await File.WriteAllTextAsync(temporaryPath, script, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
            // Never replace a file that appeared while the temporary script was being written.
            File.Move(temporaryPath, fullPath, overwrite: false);
        }
        finally { if (File.Exists(temporaryPath)) File.Delete(temporaryPath); }
    }

    private static string Literal(string value) => value.Replace("{", "{{", StringComparison.Ordinal);
    private static string SetupValue(string value) => "\"" + value + "\"";
    private static string Parameter(string value) => "\"" + value.Replace("\"", "\"\"", StringComparison.Ordinal) + "\"";
    private static InvalidDataException Error(string key)
    {
        var error = new InvalidDataException(new StudioLocalizer()[key]);
        error.Data["Studio.ResourceKey"] = key;
        return error;
    }
}
